// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/6389aa9b3725b78c98cb4d19b1948879bd2d175c/esprima/esprima.d.ts

declare module "esprima" {
    import { Program, Node } from 'estree';

    export const version: string;

    export function parse(code: string, options?: Options): Program;
    export function tokenize(code: string, options?: Options): Array<Token>;

    export interface Token {
        type: string;
        value: string;
    }

    export interface Comment extends Node {
        value: string;
    }

    export interface Options {
        loc?: boolean;
        range?: boolean;
        raw?: boolean;
        tokens?: boolean;
        comment?: boolean;
        attachComment?: boolean;
        tolerant?: boolean;
        source?: boolean;
        sourceType?: 'script' | 'module';
    }
}
